module.exports = {
    BD: {
      country_name: "Bangladesh",
      iso2_code: "BD",
      iso3_code: "BGD",
      phone_code: "880",
      currency_code: "BDT",
    },
    BE: {
      country_name: "Belgium",
      iso2_code: "BE",
      iso3_code: "BEL",
      phone_code: "32",
      currency_code: "EUR",
    },
    BF: {
      country_name: "Burkina Faso",
      iso2_code: "BF",
      iso3_code: "BFA",
      phone_code: "226",
      currency_code: "XOF",
    },
    BG: {
      country_name: "Bulgaria",
      iso2_code: "BG",
      iso3_code: "BGR",
      phone_code: "359",
      currency_code: "BGN",
    },
    BA: {
      country_name: "Bosnia and Herzegovina",
      iso2_code: "BA",
      iso3_code: "BIH",
      phone_code: "387",
      currency_code: "BAM",
    },
    BB: {
      country_name: "Barbados",
      iso2_code: "BB",
      iso3_code: "BRB",
      phone_code: "+1-246",
      currency_code: "BBD",
    },
    WF: {
      country_name: "Wallis and Futuna",
      iso2_code: "WF",
      iso3_code: "WLF",
      phone_code: "681",
      currency_code: "XPF",
    },
    BL: {
      country_name: "Saint Barthelemy",
      iso2_code: "BL",
      iso3_code: "BLM",
      phone_code: "590",
      currency_code: "EUR",
    },
    BM: {
      country_name: "Bermuda",
      iso2_code: "BM",
      iso3_code: "BMU",
      phone_code: "+1-441",
      currency_code: "BMD",
    },
    BN: {
      country_name: "Brunei",
      iso2_code: "BN",
      iso3_code: "BRN",
      phone_code: "673",
      currency_code: "BND",
    },
    BO: {
      country_name: "Bolivia",
      iso2_code: "BO",
      iso3_code: "BOL",
      phone_code: "591",
      currency_code: "BOB",
    },
    BH: {
      country_name: "Bahrain",
      iso2_code: "BH",
      iso3_code: "BHR",
      phone_code: "973",
      currency_code: "BHD",
    },
    BI: {
      country_name: "Burundi",
      iso2_code: "BI",
      iso3_code: "BDI",
      phone_code: "257",
      currency_code: "BIF",
    },
    BJ: {
      country_name: "Benin",
      iso2_code: "BJ",
      iso3_code: "BEN",
      phone_code: "229",
      currency_code: "XOF",
    },
    BT: {
      country_name: "Bhutan",
      iso2_code: "BT",
      iso3_code: "BTN",
      phone_code: "975",
      currency_code: "BTN",
    },
    JM: {
      country_name: "Jamaica",
      iso2_code: "JM",
      iso3_code: "JAM",
      phone_code: "+1-876",
      currency_code: "JMD",
    },
    BV: {
      country_name: "Bouvet Island",
      iso2_code: "BV",
      iso3_code: "BVT",
      phone_code: "",
      currency_code: "NOK",
    },
    BW: {
      country_name: "Botswana",
      iso2_code: "BW",
      iso3_code: "BWA",
      phone_code: "267",
      currency_code: "BWP",
    },
    WS: {
      country_name: "Samoa",
      iso2_code: "WS",
      iso3_code: "WSM",
      phone_code: "685",
      currency_code: "WST",
    },
    BQ: {
      country_name: "Bonaire, Saint Eustatius and Saba ",
      iso2_code: "BQ",
      iso3_code: "BES",
      phone_code: "599",
      currency_code: "USD",
    },
    BR: {
      country_name: "Brazil",
      iso2_code: "BR",
      iso3_code: "BRA",
      phone_code: "55",
      currency_code: "BRL",
    },
    BS: {
      country_name: "Bahamas",
      iso2_code: "BS",
      iso3_code: "BHS",
      phone_code: "+1-242",
      currency_code: "BSD",
    },
    JE: {
      country_name: "Jersey",
      iso2_code: "JE",
      iso3_code: "JEY",
      phone_code: "+44-1534",
      currency_code: "GBP",
    },
    BY: {
      country_name: "Belarus",
      iso2_code: "BY",
      iso3_code: "BLR",
      phone_code: "375",
      currency_code: "BYR",
    },
    BZ: {
      country_name: "Belize",
      iso2_code: "BZ",
      iso3_code: "BLZ",
      phone_code: "501",
      currency_code: "BZD",
    },
    RU: {
      country_name: "Russia",
      iso2_code: "RU",
      iso3_code: "RUS",
      phone_code: "7",
      currency_code: "RUB",
    },
    RW: {
      country_name: "Rwanda",
      iso2_code: "RW",
      iso3_code: "RWA",
      phone_code: "250",
      currency_code: "RWF",
    },
    RS: {
      country_name: "Serbia",
      iso2_code: "RS",
      iso3_code: "SRB",
      phone_code: "381",
      currency_code: "RSD",
    },
    TL: {
      country_name: "East Timor",
      iso2_code: "TL",
      iso3_code: "TLS",
      phone_code: "670",
      currency_code: "USD",
    },
    RE: {
      country_name: "Reunion",
      iso2_code: "RE",
      iso3_code: "REU",
      phone_code: "262",
      currency_code: "EUR",
    },
    TM: {
      country_name: "Turkmenistan",
      iso2_code: "TM",
      iso3_code: "TKM",
      phone_code: "993",
      currency_code: "TMT",
    },
    TJ: {
      country_name: "Tajikistan",
      iso2_code: "TJ",
      iso3_code: "TJK",
      phone_code: "992",
      currency_code: "TJS",
    },
    RO: {
      country_name: "Romania",
      iso2_code: "RO",
      iso3_code: "ROU",
      phone_code: "40",
      currency_code: "RON",
    },
    TK: {
      country_name: "Tokelau",
      iso2_code: "TK",
      iso3_code: "TKL",
      phone_code: "690",
      currency_code: "NZD",
    },
    GW: {
      country_name: "Guinea-Bissau",
      iso2_code: "GW",
      iso3_code: "GNB",
      phone_code: "245",
      currency_code: "XOF",
    },
    GU: {
      country_name: "Guam",
      iso2_code: "GU",
      iso3_code: "GUM",
      phone_code: "+1-671",
      currency_code: "USD",
    },
    GT: {
      country_name: "Guatemala",
      iso2_code: "GT",
      iso3_code: "GTM",
      phone_code: "502",
      currency_code: "GTQ",
    },
    GS: {
      country_name: "South Georgia and the South Sandwich Islands",
      iso2_code: "GS",
      iso3_code: "SGS",
      phone_code: "",
      currency_code: "GBP",
    },
    GR: {
      country_name: "Greece",
      iso2_code: "GR",
      iso3_code: "GRC",
      phone_code: "30",
      currency_code: "EUR",
    },
    GQ: {
      country_name: "Equatorial Guinea",
      iso2_code: "GQ",
      iso3_code: "GNQ",
      phone_code: "240",
      currency_code: "XAF",
    },
    GP: {
      country_name: "Guadeloupe",
      iso2_code: "GP",
      iso3_code: "GLP",
      phone_code: "590",
      currency_code: "EUR",
    },
    JP: {
      country_name: "Japan",
      iso2_code: "JP",
      iso3_code: "JPN",
      phone_code: "81",
      currency_code: "JPY",
    },
    GY: {
      country_name: "Guyana",
      iso2_code: "GY",
      iso3_code: "GUY",
      phone_code: "592",
      currency_code: "GYD",
    },
    GG: {
      country_name: "Guernsey",
      iso2_code: "GG",
      iso3_code: "GGY",
      phone_code: "+44-1481",
      currency_code: "GBP",
    },
    GF: {
      country_name: "French Guiana",
      iso2_code: "GF",
      iso3_code: "GUF",
      phone_code: "594",
      currency_code: "EUR",
    },
    GE: {
      country_name: "Georgia",
      iso2_code: "GE",
      iso3_code: "GEO",
      phone_code: "995",
      currency_code: "GEL",
    },
    GD: {
      country_name: "Grenada",
      iso2_code: "GD",
      iso3_code: "GRD",
      phone_code: "+1-473",
      currency_code: "XCD",
    },
    GB: {
      country_name: "United Kingdom",
      iso2_code: "GB",
      iso3_code: "GBR",
      phone_code: "44",
      currency_code: "GBP",
    },
    GA: {
      country_name: "Gabon",
      iso2_code: "GA",
      iso3_code: "GAB",
      phone_code: "241",
      currency_code: "XAF",
    },
    SV: {
      country_name: "El Salvador",
      iso2_code: "SV",
      iso3_code: "SLV",
      phone_code: "503",
      currency_code: "USD",
    },
    GN: {
      country_name: "Guinea",
      iso2_code: "GN",
      iso3_code: "GIN",
      phone_code: "224",
      currency_code: "GNF",
    },
    GM: {
      country_name: "Gambia",
      iso2_code: "GM",
      iso3_code: "GMB",
      phone_code: "220",
      currency_code: "GMD",
    },
    GL: {
      country_name: "Greenland",
      iso2_code: "GL",
      iso3_code: "GRL",
      phone_code: "299",
      currency_code: "DKK",
    },
    GI: {
      country_name: "Gibraltar",
      iso2_code: "GI",
      iso3_code: "GIB",
      phone_code: "350",
      currency_code: "GIP",
    },
    GH: {
      country_name: "Ghana",
      iso2_code: "GH",
      iso3_code: "GHA",
      phone_code: "233",
      currency_code: "GHS",
    },
    OM: {
      country_name: "Oman",
      iso2_code: "OM",
      iso3_code: "OMN",
      phone_code: "968",
      currency_code: "OMR",
    },
    TN: {
      country_name: "Tunisia",
      iso2_code: "TN",
      iso3_code: "TUN",
      phone_code: "216",
      currency_code: "TND",
    },
    JO: {
      country_name: "Jordan",
      iso2_code: "JO",
      iso3_code: "JOR",
      phone_code: "962",
      currency_code: "JOD",
    },
    HR: {
      country_name: "Croatia",
      iso2_code: "HR",
      iso3_code: "HRV",
      phone_code: "385",
      currency_code: "HRK",
    },
    HT: {
      country_name: "Haiti",
      iso2_code: "HT",
      iso3_code: "HTI",
      phone_code: "509",
      currency_code: "HTG",
    },
    HU: {
      country_name: "Hungary",
      iso2_code: "HU",
      iso3_code: "HUN",
      phone_code: "36",
      currency_code: "HUF",
    },
    HK: {
      country_name: "Hong Kong",
      iso2_code: "HK",
      iso3_code: "HKG",
      phone_code: "852",
      currency_code: "HKD",
    },
    HN: {
      country_name: "Honduras",
      iso2_code: "HN",
      iso3_code: "HND",
      phone_code: "504",
      currency_code: "HNL",
    },
    HM: {
      country_name: "Heard Island and McDonald Islands",
      iso2_code: "HM",
      iso3_code: "HMD",
      phone_code: " ",
      currency_code: "AUD",
    },
    VE: {
      country_name: "Venezuela",
      iso2_code: "VE",
      iso3_code: "VEN",
      phone_code: "58",
      currency_code: "VEF",
    },
    PR: {
      country_name: "Puerto Rico",
      iso2_code: "PR",
      iso3_code: "PRI",
      phone_code: "+1-787 and 1-939",
      currency_code: "USD",
    },
    PS: {
      country_name: "Palestinian Territory",
      iso2_code: "PS",
      iso3_code: "PSE",
      phone_code: "970",
      currency_code: "ILS",
    },
    PW: {
      country_name: "Palau",
      iso2_code: "PW",
      iso3_code: "PLW",
      phone_code: "680",
      currency_code: "USD",
    },
    PT: {
      country_name: "Portugal",
      iso2_code: "PT",
      iso3_code: "PRT",
      phone_code: "351",
      currency_code: "EUR",
    },
    SJ: {
      country_name: "Svalbard and Jan Mayen",
      iso2_code: "SJ",
      iso3_code: "SJM",
      phone_code: "47",
      currency_code: "NOK",
    },
    PY: {
      country_name: "Paraguay",
      iso2_code: "PY",
      iso3_code: "PRY",
      phone_code: "595",
      currency_code: "PYG",
    },
    IQ: {
      country_name: "Iraq",
      iso2_code: "IQ",
      iso3_code: "IRQ",
      phone_code: "964",
      currency_code: "IQD",
    },
    PA: {
      country_name: "Panama",
      iso2_code: "PA",
      iso3_code: "PAN",
      phone_code: "507",
      currency_code: "PAB",
    },
    PF: {
      country_name: "French Polynesia",
      iso2_code: "PF",
      iso3_code: "PYF",
      phone_code: "689",
      currency_code: "XPF",
    },
    PG: {
      country_name: "Papua New Guinea",
      iso2_code: "PG",
      iso3_code: "PNG",
      phone_code: "675",
      currency_code: "PGK",
    },
    PE: {
      country_name: "Peru",
      iso2_code: "PE",
      iso3_code: "PER",
      phone_code: "51",
      currency_code: "PEN",
    },
    PK: {
      country_name: "Pakistan",
      iso2_code: "PK",
      iso3_code: "PAK",
      phone_code: "92",
      currency_code: "PKR",
    },
    PH: {
      country_name: "Philippines",
      iso2_code: "PH",
      iso3_code: "PHL",
      phone_code: "63",
      currency_code: "PHP",
    },
    PN: {
      country_name: "Pitcairn",
      iso2_code: "PN",
      iso3_code: "PCN",
      phone_code: "870",
      currency_code: "NZD",
    },
    PL: {
      country_name: "Poland",
      iso2_code: "PL",
      iso3_code: "POL",
      phone_code: "48",
      currency_code: "PLN",
    },
    PM: {
      country_name: "Saint Pierre and Miquelon",
      iso2_code: "PM",
      iso3_code: "SPM",
      phone_code: "508",
      currency_code: "EUR",
    },
    ZM: {
      country_name: "Zambia",
      iso2_code: "ZM",
      iso3_code: "ZMB",
      phone_code: "260",
      currency_code: "ZMK",
    },
    EH: {
      country_name: "Western Sahara",
      iso2_code: "EH",
      iso3_code: "ESH",
      phone_code: "212",
      currency_code: "MAD",
    },
    EE: {
      country_name: "Estonia",
      iso2_code: "EE",
      iso3_code: "EST",
      phone_code: "372",
      currency_code: "EUR",
    },
    EG: {
      country_name: "Egypt",
      iso2_code: "EG",
      iso3_code: "EGY",
      phone_code: "20",
      currency_code: "EGP",
    },
    ZA: {
      country_name: "South Africa",
      iso2_code: "ZA",
      iso3_code: "ZAF",
      phone_code: "27",
      currency_code: "ZAR",
    },
    EC: {
      country_name: "Ecuador",
      iso2_code: "EC",
      iso3_code: "ECU",
      phone_code: "593",
      currency_code: "USD",
    },
    IT: {
      country_name: "Italy",
      iso2_code: "IT",
      iso3_code: "ITA",
      phone_code: "39",
      currency_code: "EUR",
    },
    VN: {
      country_name: "Vietnam",
      iso2_code: "VN",
      iso3_code: "VNM",
      phone_code: "84",
      currency_code: "VND",
    },
    SB: {
      country_name: "Solomon Islands",
      iso2_code: "SB",
      iso3_code: "SLB",
      phone_code: "677",
      currency_code: "SBD",
    },
    ET: {
      country_name: "Ethiopia",
      iso2_code: "ET",
      iso3_code: "ETH",
      phone_code: "251",
      currency_code: "ETB",
    },
    SO: {
      country_name: "Somalia",
      iso2_code: "SO",
      iso3_code: "SOM",
      phone_code: "252",
      currency_code: "SOS",
    },
    ZW: {
      country_name: "Zimbabwe",
      iso2_code: "ZW",
      iso3_code: "ZWE",
      phone_code: "263",
      currency_code: "ZWL",
    },
    SA: {
      country_name: "Saudi Arabia",
      iso2_code: "SA",
      iso3_code: "SAU",
      phone_code: "966",
      currency_code: "SAR",
    },
    ES: {
      country_name: "Spain",
      iso2_code: "ES",
      iso3_code: "ESP",
      phone_code: "34",
      currency_code: "EUR",
    },
    ER: {
      country_name: "Eritrea",
      iso2_code: "ER",
      iso3_code: "ERI",
      phone_code: "291",
      currency_code: "ERN",
    },
    ME: {
      country_name: "Montenegro",
      iso2_code: "ME",
      iso3_code: "MNE",
      phone_code: "382",
      currency_code: "EUR",
    },
    MD: {
      country_name: "Moldova",
      iso2_code: "MD",
      iso3_code: "MDA",
      phone_code: "373",
      currency_code: "MDL",
    },
    MG: {
      country_name: "Madagascar",
      iso2_code: "MG",
      iso3_code: "MDG",
      phone_code: "261",
      currency_code: "MGA",
    },
    MF: {
      country_name: "Saint Martin",
      iso2_code: "MF",
      iso3_code: "MAF",
      phone_code: "590",
      currency_code: "EUR",
    },
    MA: {
      country_name: "Morocco",
      iso2_code: "MA",
      iso3_code: "MAR",
      phone_code: "212",
      currency_code: "MAD",
    },
    MC: {
      country_name: "Monaco",
      iso2_code: "MC",
      iso3_code: "MCO",
      phone_code: "377",
      currency_code: "EUR",
    },
    UZ: {
      country_name: "Uzbekistan",
      iso2_code: "UZ",
      iso3_code: "UZB",
      phone_code: "998",
      currency_code: "UZS",
    },
    MM: {
      country_name: "Myanmar",
      iso2_code: "MM",
      iso3_code: "MMR",
      phone_code: "95",
      currency_code: "MMK",
    },
    ML: {
      country_name: "Mali",
      iso2_code: "ML",
      iso3_code: "MLI",
      phone_code: "223",
      currency_code: "XOF",
    },
    MO: {
      country_name: "Macao",
      iso2_code: "MO",
      iso3_code: "MAC",
      phone_code: "853",
      currency_code: "MOP",
    },
    MN: {
      country_name: "Mongolia",
      iso2_code: "MN",
      iso3_code: "MNG",
      phone_code: "976",
      currency_code: "MNT",
    },
    MH: {
      country_name: "Marshall Islands",
      iso2_code: "MH",
      iso3_code: "MHL",
      phone_code: "692",
      currency_code: "USD",
    },
    MK: {
      country_name: "Macedonia",
      iso2_code: "MK",
      iso3_code: "MKD",
      phone_code: "389",
      currency_code: "MKD",
    },
    MU: {
      country_name: "Mauritius",
      iso2_code: "MU",
      iso3_code: "MUS",
      phone_code: "230",
      currency_code: "MUR",
    },
    MT: {
      country_name: "Malta",
      iso2_code: "MT",
      iso3_code: "MLT",
      phone_code: "356",
      currency_code: "EUR",
    },
    MW: {
      country_name: "Malawi",
      iso2_code: "MW",
      iso3_code: "MWI",
      phone_code: "265",
      currency_code: "MWK",
    },
    MV: {
      country_name: "Maldives",
      iso2_code: "MV",
      iso3_code: "MDV",
      phone_code: "960",
      currency_code: "MVR",
    },
    MQ: {
      country_name: "Martinique",
      iso2_code: "MQ",
      iso3_code: "MTQ",
      phone_code: "596",
      currency_code: "EUR",
    },
    MP: {
      country_name: "Northern Mariana Islands",
      iso2_code: "MP",
      iso3_code: "MNP",
      phone_code: "+1-670",
      currency_code: "USD",
    },
    MS: {
      country_name: "Montserrat",
      iso2_code: "MS",
      iso3_code: "MSR",
      phone_code: "+1-664",
      currency_code: "XCD",
    },
    MR: {
      country_name: "Mauritania",
      iso2_code: "MR",
      iso3_code: "MRT",
      phone_code: "222",
      currency_code: "MRO",
    },
    IM: {
      country_name: "Isle of Man",
      iso2_code: "IM",
      iso3_code: "IMN",
      phone_code: "+44-1624",
      currency_code: "GBP",
    },
    UG: {
      country_name: "Uganda",
      iso2_code: "UG",
      iso3_code: "UGA",
      phone_code: "256",
      currency_code: "UGX",
    },
    TZ: {
      country_name: "Tanzania",
      iso2_code: "TZ",
      iso3_code: "TZA",
      phone_code: "255",
      currency_code: "TZS",
    },
    MY: {
      country_name: "Malaysia",
      iso2_code: "MY",
      iso3_code: "MYS",
      phone_code: "60",
      currency_code: "MYR",
    },
    MX: {
      country_name: "Mexico",
      iso2_code: "MX",
      iso3_code: "MEX",
      phone_code: "52",
      currency_code: "MXN",
    },
    IL: {
      country_name: "Israel",
      iso2_code: "IL",
      iso3_code: "ISR",
      phone_code: "972",
      currency_code: "ILS",
    },
    FR: {
      country_name: "France",
      iso2_code: "FR",
      iso3_code: "FRA",
      phone_code: "33",
      currency_code: "EUR",
    },
    IO: {
      country_name: "British Indian Ocean Territory",
      iso2_code: "IO",
      iso3_code: "IOT",
      phone_code: "246",
      currency_code: "USD",
    },
    SH: {
      country_name: "Saint Helena",
      iso2_code: "SH",
      iso3_code: "SHN",
      phone_code: "290",
      currency_code: "SHP",
    },
    FI: {
      country_name: "Finland",
      iso2_code: "FI",
      iso3_code: "FIN",
      phone_code: "358",
      currency_code: "EUR",
    },
    FJ: {
      country_name: "Fiji",
      iso2_code: "FJ",
      iso3_code: "FJI",
      phone_code: "679",
      currency_code: "FJD",
    },
    FK: {
      country_name: "Falkland Islands",
      iso2_code: "FK",
      iso3_code: "FLK",
      phone_code: "500",
      currency_code: "FKP",
    },
    FM: {
      country_name: "Micronesia",
      iso2_code: "FM",
      iso3_code: "FSM",
      phone_code: "691",
      currency_code: "USD",
    },
    FO: {
      country_name: "Faroe Islands",
      iso2_code: "FO",
      iso3_code: "FRO",
      phone_code: "298",
      currency_code: "DKK",
    },
    NI: {
      country_name: "Nicaragua",
      iso2_code: "NI",
      iso3_code: "NIC",
      phone_code: "505",
      currency_code: "NIO",
    },
    NL: {
      country_name: "Netherlands",
      iso2_code: "NL",
      iso3_code: "NLD",
      phone_code: "31",
      currency_code: "EUR",
    },
    NO: {
      country_name: "Norway",
      iso2_code: "NO",
      iso3_code: "NOR",
      phone_code: "47",
      currency_code: "NOK",
    },
    NA: {
      country_name: "Namibia",
      iso2_code: "NA",
      iso3_code: "NAM",
      phone_code: "264",
      currency_code: "NAD",
    },
    VU: {
      country_name: "Vanuatu",
      iso2_code: "VU",
      iso3_code: "VUT",
      phone_code: "678",
      currency_code: "VUV",
    },
    NC: {
      country_name: "New Caledonia",
      iso2_code: "NC",
      iso3_code: "NCL",
      phone_code: "687",
      currency_code: "XPF",
    },
    NE: {
      country_name: "Niger",
      iso2_code: "NE",
      iso3_code: "NER",
      phone_code: "227",
      currency_code: "XOF",
    },
    NF: {
      country_name: "Norfolk Island",
      iso2_code: "NF",
      iso3_code: "NFK",
      phone_code: "672",
      currency_code: "AUD",
    },
    NG: {
      country_name: "Nigeria",
      iso2_code: "NG",
      iso3_code: "NGA",
      phone_code: "234",
      currency_code: "NGN",
    },
    NZ: {
      country_name: "New Zealand",
      iso2_code: "NZ",
      iso3_code: "NZL",
      phone_code: "64",
      currency_code: "NZD",
    },
    NP: {
      country_name: "Nepal",
      iso2_code: "NP",
      iso3_code: "NPL",
      phone_code: "977",
      currency_code: "NPR",
    },
    NR: {
      country_name: "Nauru",
      iso2_code: "NR",
      iso3_code: "NRU",
      phone_code: "674",
      currency_code: "AUD",
    },
    NU: {
      country_name: "Niue",
      iso2_code: "NU",
      iso3_code: "NIU",
      phone_code: "683",
      currency_code: "NZD",
    },
    CK: {
      country_name: "Cook Islands",
      iso2_code: "CK",
      iso3_code: "COK",
      phone_code: "682",
      currency_code: "NZD",
    },
    XK: {
      country_name: "Kosovo",
      iso2_code: "XK",
      iso3_code: "XKX",
      phone_code: "",
      currency_code: "EUR",
    },
    CI: {
      country_name: "Ivory Coast",
      iso2_code: "CI",
      iso3_code: "CIV",
      phone_code: "225",
      currency_code: "XOF",
    },
    CH: {
      country_name: "Switzerland",
      iso2_code: "CH",
      iso3_code: "CHE",
      phone_code: "41",
      currency_code: "CHF",
    },
    CO: {
      country_name: "Colombia",
      iso2_code: "CO",
      iso3_code: "COL",
      phone_code: "57",
      currency_code: "COP",
    },
    CN: {
      country_name: "China",
      iso2_code: "CN",
      iso3_code: "CHN",
      phone_code: "86",
      currency_code: "CNY",
    },
    CM: {
      country_name: "Cameroon",
      iso2_code: "CM",
      iso3_code: "CMR",
      phone_code: "237",
      currency_code: "XAF",
    },
    CL: {
      country_name: "Chile",
      iso2_code: "CL",
      iso3_code: "CHL",
      phone_code: "56",
      currency_code: "CLP",
    },
    CC: {
      country_name: "Cocos Islands",
      iso2_code: "CC",
      iso3_code: "CCK",
      phone_code: "61",
      currency_code: "AUD",
    },
    CA: {
      country_name: "Canada",
      iso2_code: "CA",
      iso3_code: "CAN",
      phone_code: "1",
      currency_code: "CAD",
    },
    CG: {
      country_name: "Republic of the Congo",
      iso2_code: "CG",
      iso3_code: "COG",
      phone_code: "242",
      currency_code: "XAF",
    },
    CF: {
      country_name: "Central African Republic",
      iso2_code: "CF",
      iso3_code: "CAF",
      phone_code: "236",
      currency_code: "XAF",
    },
    CD: {
      country_name: "Democratic Republic of the Congo",
      iso2_code: "CD",
      iso3_code: "COD",
      phone_code: "243",
      currency_code: "CDF",
    },
    CZ: {
      country_name: "Czech Republic",
      iso2_code: "CZ",
      iso3_code: "CZE",
      phone_code: "420",
      currency_code: "CZK",
    },
    CY: {
      country_name: "Cyprus",
      iso2_code: "CY",
      iso3_code: "CYP",
      phone_code: "357",
      currency_code: "EUR",
    },
    CX: {
      country_name: "Christmas Island",
      iso2_code: "CX",
      iso3_code: "CXR",
      phone_code: "61",
      currency_code: "AUD",
    },
    CR: {
      country_name: "Costa Rica",
      iso2_code: "CR",
      iso3_code: "CRI",
      phone_code: "506",
      currency_code: "CRC",
    },
    CW: {
      country_name: "Curacao",
      iso2_code: "CW",
      iso3_code: "CUW",
      phone_code: "599",
      currency_code: "ANG",
    },
    CV: {
      country_name: "Cape Verde",
      iso2_code: "CV",
      iso3_code: "CPV",
      phone_code: "238",
      currency_code: "CVE",
    },
    CU: {
      country_name: "Cuba",
      iso2_code: "CU",
      iso3_code: "CUB",
      phone_code: "53",
      currency_code: "CUP",
    },
    SZ: {
      country_name: "Swaziland",
      iso2_code: "SZ",
      iso3_code: "SWZ",
      phone_code: "268",
      currency_code: "SZL",
    },
    SY: {
      country_name: "Syria",
      iso2_code: "SY",
      iso3_code: "SYR",
      phone_code: "963",
      currency_code: "SYP",
    },
    SX: {
      country_name: "Sint Maarten",
      iso2_code: "SX",
      iso3_code: "SXM",
      phone_code: "599",
      currency_code: "ANG",
    },
    KG: {
      country_name: "Kyrgyzstan",
      iso2_code: "KG",
      iso3_code: "KGZ",
      phone_code: "996",
      currency_code: "KGS",
    },
    KE: {
      country_name: "Kenya",
      iso2_code: "KE",
      iso3_code: "KEN",
      phone_code: "254",
      currency_code: "KES",
    },
    SS: {
      country_name: "South Sudan",
      iso2_code: "SS",
      iso3_code: "SSD",
      phone_code: "211",
      currency_code: "SSP",
    },
    SR: {
      country_name: "Suriname",
      iso2_code: "SR",
      iso3_code: "SUR",
      phone_code: "597",
      currency_code: "SRD",
    },
    KI: {
      country_name: "Kiribati",
      iso2_code: "KI",
      iso3_code: "KIR",
      phone_code: "686",
      currency_code: "AUD",
    },
    KH: {
      country_name: "Cambodia",
      iso2_code: "KH",
      iso3_code: "KHM",
      phone_code: "855",
      currency_code: "KHR",
    },
    KN: {
      country_name: "Saint Kitts and Nevis",
      iso2_code: "KN",
      iso3_code: "KNA",
      phone_code: "+1-869",
      currency_code: "XCD",
    },
    KM: {
      country_name: "Comoros",
      iso2_code: "KM",
      iso3_code: "COM",
      phone_code: "269",
      currency_code: "KMF",
    },
    ST: {
      country_name: "Sao Tome and Principe",
      iso2_code: "ST",
      iso3_code: "STP",
      phone_code: "239",
      currency_code: "STD",
    },
    SK: {
      country_name: "Slovakia",
      iso2_code: "SK",
      iso3_code: "SVK",
      phone_code: "421",
      currency_code: "EUR",
    },
    KR: {
      country_name: "South Korea",
      iso2_code: "KR",
      iso3_code: "KOR",
      phone_code: "82",
      currency_code: "KRW",
    },
    SI: {
      country_name: "Slovenia",
      iso2_code: "SI",
      iso3_code: "SVN",
      phone_code: "386",
      currency_code: "EUR",
    },
    KP: {
      country_name: "North Korea",
      iso2_code: "KP",
      iso3_code: "PRK",
      phone_code: "850",
      currency_code: "KPW",
    },
    KW: {
      country_name: "Kuwait",
      iso2_code: "KW",
      iso3_code: "KWT",
      phone_code: "965",
      currency_code: "KWD",
    },
    SN: {
      country_name: "Senegal",
      iso2_code: "SN",
      iso3_code: "SEN",
      phone_code: "221",
      currency_code: "XOF",
    },
    SM: {
      country_name: "San Marino",
      iso2_code: "SM",
      iso3_code: "SMR",
      phone_code: "378",
      currency_code: "EUR",
    },
    SL: {
      country_name: "Sierra Leone",
      iso2_code: "SL",
      iso3_code: "SLE",
      phone_code: "232",
      currency_code: "SLL",
    },
    SC: {
      country_name: "Seychelles",
      iso2_code: "SC",
      iso3_code: "SYC",
      phone_code: "248",
      currency_code: "SCR",
    },
    KZ: {
      country_name: "Kazakhstan",
      iso2_code: "KZ",
      iso3_code: "KAZ",
      phone_code: "7",
      currency_code: "KZT",
    },
    KY: {
      country_name: "Cayman Islands",
      iso2_code: "KY",
      iso3_code: "CYM",
      phone_code: "+1-345",
      currency_code: "KYD",
    },
    SG: {
      country_name: "Singapore",
      iso2_code: "SG",
      iso3_code: "SGP",
      phone_code: "65",
      currency_code: "SGD",
    },
    SE: {
      country_name: "Sweden",
      iso2_code: "SE",
      iso3_code: "SWE",
      phone_code: "46",
      currency_code: "SEK",
    },
    SD: {
      country_name: "Sudan",
      iso2_code: "SD",
      iso3_code: "SDN",
      phone_code: "249",
      currency_code: "SDG",
    },
    DO: {
      country_name: "Dominican Republic",
      iso2_code: "DO",
      iso3_code: "DOM",
      phone_code: "+1-809 and 1-829",
      currency_code: "DOP",
    },
    DM: {
      country_name: "Dominica",
      iso2_code: "DM",
      iso3_code: "DMA",
      phone_code: "+1-767",
      currency_code: "XCD",
    },
    DJ: {
      country_name: "Djibouti",
      iso2_code: "DJ",
      iso3_code: "DJI",
      phone_code: "253",
      currency_code: "DJF",
    },
    DK: {
      country_name: "Denmark",
      iso2_code: "DK",
      iso3_code: "DNK",
      phone_code: "45",
      currency_code: "DKK",
    },
    VG: {
      country_name: "British Virgin Islands",
      iso2_code: "VG",
      iso3_code: "VGB",
      phone_code: "+1-284",
      currency_code: "USD",
    },
    DE: {
      country_name: "Germany",
      iso2_code: "DE",
      iso3_code: "DEU",
      phone_code: "49",
      currency_code: "EUR",
    },
    YE: {
      country_name: "Yemen",
      iso2_code: "YE",
      iso3_code: "YEM",
      phone_code: "967",
      currency_code: "YER",
    },
    DZ: {
      country_name: "Algeria",
      iso2_code: "DZ",
      iso3_code: "DZA",
      phone_code: "213",
      currency_code: "DZD",
    },
    US: {
      country_name: "United States",
      iso2_code: "US",
      iso3_code: "USA",
      phone_code: "1",
      currency_code: "USD",
    },
    UY: {
      country_name: "Uruguay",
      iso2_code: "UY",
      iso3_code: "URY",
      phone_code: "598",
      currency_code: "UYU",
    },
    YT: {
      country_name: "Mayotte",
      iso2_code: "YT",
      iso3_code: "MYT",
      phone_code: "262",
      currency_code: "EUR",
    },
    UM: {
      country_name: "United States Minor Outlying Islands",
      iso2_code: "UM",
      iso3_code: "UMI",
      phone_code: "1",
      currency_code: "USD",
    },
    LB: {
      country_name: "Lebanon",
      iso2_code: "LB",
      iso3_code: "LBN",
      phone_code: "961",
      currency_code: "LBP",
    },
    LC: {
      country_name: "Saint Lucia",
      iso2_code: "LC",
      iso3_code: "LCA",
      phone_code: "+1-758",
      currency_code: "XCD",
    },
    LA: {
      country_name: "Laos",
      iso2_code: "LA",
      iso3_code: "LAO",
      phone_code: "856",
      currency_code: "LAK",
    },
    TV: {
      country_name: "Tuvalu",
      iso2_code: "TV",
      iso3_code: "TUV",
      phone_code: "688",
      currency_code: "AUD",
    },
    TW: {
      country_name: "Taiwan",
      iso2_code: "TW",
      iso3_code: "TWN",
      phone_code: "886",
      currency_code: "TWD",
    },
    TT: {
      country_name: "Trinidad and Tobago",
      iso2_code: "TT",
      iso3_code: "TTO",
      phone_code: "+1-868",
      currency_code: "TTD",
    },
    TR: {
      country_name: "Turkey",
      iso2_code: "TR",
      iso3_code: "TUR",
      phone_code: "90",
      currency_code: "TRY",
    },
    LK: {
      country_name: "Sri Lanka",
      iso2_code: "LK",
      iso3_code: "LKA",
      phone_code: "94",
      currency_code: "LKR",
    },
    LI: {
      country_name: "Liechtenstein",
      iso2_code: "LI",
      iso3_code: "LIE",
      phone_code: "423",
      currency_code: "CHF",
    },
    LV: {
      country_name: "Latvia",
      iso2_code: "LV",
      iso3_code: "LVA",
      phone_code: "371",
      currency_code: "EUR",
    },
    TO: {
      country_name: "Tonga",
      iso2_code: "TO",
      iso3_code: "TON",
      phone_code: "676",
      currency_code: "TOP",
    },
    LT: {
      country_name: "Lithuania",
      iso2_code: "LT",
      iso3_code: "LTU",
      phone_code: "370",
      currency_code: "LTL",
    },
    LU: {
      country_name: "Luxembourg",
      iso2_code: "LU",
      iso3_code: "LUX",
      phone_code: "352",
      currency_code: "EUR",
    },
    LR: {
      country_name: "Liberia",
      iso2_code: "LR",
      iso3_code: "LBR",
      phone_code: "231",
      currency_code: "LRD",
    },
    LS: {
      country_name: "Lesotho",
      iso2_code: "LS",
      iso3_code: "LSO",
      phone_code: "266",
      currency_code: "LSL",
    },
    TH: {
      country_name: "Thailand",
      iso2_code: "TH",
      iso3_code: "THA",
      phone_code: "66",
      currency_code: "THB",
    },
    TF: {
      country_name: "French Southern Territories",
      iso2_code: "TF",
      iso3_code: "ATF",
      phone_code: "",
      currency_code: "EUR",
    },
    TG: {
      country_name: "Togo",
      iso2_code: "TG",
      iso3_code: "TGO",
      phone_code: "228",
      currency_code: "XOF",
    },
    TD: {
      country_name: "Chad",
      iso2_code: "TD",
      iso3_code: "TCD",
      phone_code: "235",
      currency_code: "XAF",
    },
    TC: {
      country_name: "Turks and Caicos Islands",
      iso2_code: "TC",
      iso3_code: "TCA",
      phone_code: "+1-649",
      currency_code: "USD",
    },
    LY: {
      country_name: "Libya",
      iso2_code: "LY",
      iso3_code: "LBY",
      phone_code: "218",
      currency_code: "LYD",
    },
    VA: {
      country_name: "Vatican",
      iso2_code: "VA",
      iso3_code: "VAT",
      phone_code: "379",
      currency_code: "EUR",
    },
    VC: {
      country_name: "Saint Vincent and the Grenadines",
      iso2_code: "VC",
      iso3_code: "VCT",
      phone_code: "+1-784",
      currency_code: "XCD",
    },
    AE: {
      country_name: "United Arab Emirates",
      iso2_code: "AE",
      iso3_code: "ARE",
      phone_code: "971",
      currency_code: "AED",
    },
    AD: {
      country_name: "Andorra",
      iso2_code: "AD",
      iso3_code: "AND",
      phone_code: "376",
      currency_code: "EUR",
    },
    AG: {
      country_name: "Antigua and Barbuda",
      iso2_code: "AG",
      iso3_code: "ATG",
      phone_code: "+1-268",
      currency_code: "XCD",
    },
    AF: {
      country_name: "Afghanistan",
      iso2_code: "AF",
      iso3_code: "AFG",
      phone_code: "93",
      currency_code: "AFN",
    },
    AI: {
      country_name: "Anguilla",
      iso2_code: "AI",
      iso3_code: "AIA",
      phone_code: "+1-264",
      currency_code: "XCD",
    },
    VI: {
      country_name: "U.S. Virgin Islands",
      iso2_code: "VI",
      iso3_code: "VIR",
      phone_code: "+1-340",
      currency_code: "USD",
    },
    IS: {
      country_name: "Iceland",
      iso2_code: "IS",
      iso3_code: "ISL",
      phone_code: "354",
      currency_code: "ISK",
    },
    IR: {
      country_name: "Iran",
      iso2_code: "IR",
      iso3_code: "IRN",
      phone_code: "98",
      currency_code: "IRR",
    },
    AM: {
      country_name: "Armenia",
      iso2_code: "AM",
      iso3_code: "ARM",
      phone_code: "374",
      currency_code: "AMD",
    },
    AL: {
      country_name: "Albania",
      iso2_code: "AL",
      iso3_code: "ALB",
      phone_code: "355",
      currency_code: "ALL",
    },
    AO: {
      country_name: "Angola",
      iso2_code: "AO",
      iso3_code: "AGO",
      phone_code: "244",
      currency_code: "AOA",
    },
    AQ: {
      country_name: "Antarctica",
      iso2_code: "AQ",
      iso3_code: "ATA",
      phone_code: "",
      currency_code: "",
    },
    AS: {
      country_name: "American Samoa",
      iso2_code: "AS",
      iso3_code: "ASM",
      phone_code: "+1-684",
      currency_code: "USD",
    },
    AR: {
      country_name: "Argentina",
      iso2_code: "AR",
      iso3_code: "ARG",
      phone_code: "54",
      currency_code: "ARS",
    },
    AU: {
      country_name: "Australia",
      iso2_code: "AU",
      iso3_code: "AUS",
      phone_code: "61",
      currency_code: "AUD",
    },
    AT: {
      country_name: "Austria",
      iso2_code: "AT",
      iso3_code: "AUT",
      phone_code: "43",
      currency_code: "EUR",
    },
    AW: {
      country_name: "Aruba",
      iso2_code: "AW",
      iso3_code: "ABW",
      phone_code: "297",
      currency_code: "AWG",
    },
    IN: {
      country_name: "India",
      iso2_code: "IN",
      iso3_code: "IND",
      phone_code: "91",
      currency_code: "INR",
    },
    AX: {
      country_name: "Aland Islands",
      iso2_code: "AX",
      iso3_code: "ALA",
      phone_code: "+358-18",
      currency_code: "EUR",
    },
    AZ: {
      country_name: "Azerbaijan",
      iso2_code: "AZ",
      iso3_code: "AZE",
      phone_code: "994",
      currency_code: "AZN",
    },
    IE: {
      country_name: "Ireland",
      iso2_code: "IE",
      iso3_code: "IRL",
      phone_code: "353",
      currency_code: "EUR",
    },
    ID: {
      country_name: "Indonesia",
      iso2_code: "ID",
      iso3_code: "IDN",
      phone_code: "62",
      currency_code: "IDR",
    },
    UA: {
      country_name: "Ukraine",
      iso2_code: "UA",
      iso3_code: "UKR",
      phone_code: "380",
      currency_code: "UAH",
    },
    QA: {
      country_name: "Qatar",
      iso2_code: "QA",
      iso3_code: "QAT",
      phone_code: "974",
      currency_code: "QAR",
    },
    MZ: {
      country_name: "Mozambique",
      iso2_code: "MZ",
      iso3_code: "MOZ",
      phone_code: "258",
      currency_code: "MZN",
    },
  }
  